[phases.setup]
nixPkgs = ["python311"]
aptPkgs = []

[phases.install]
cmds = ["cd backend && python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete - frontend and backend ready'"]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8080}"
