"""add_automation_settings_table

Revision ID: 1b1fb5e0c5ec
Revises: c5feef1f39f5
Create Date: 2025-10-20 21:21:59.449394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1fb5e0c5ec'
down_revision = 'c5feef1f39f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_followup_enabled', sa.Boolean(), nullable=True),
    sa.Column('followup_delay_days', sa.Integer(), nullable=True),
    sa.Column('max_followup_count', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('browser_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_settings_id'), 'automation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_automation_settings_user_id'), 'automation_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_settings_user_id'), table_name='automation_settings')
    op.drop_index(op.f('ix_automation_settings_id'), table_name='automation_settings')
    op.drop_table('automation_settings')
    # ### end Alembic commands ###
