"""add_automation_jobs_table

Revision ID: e98a0105ab8f
Revises: 1b1fb5e0c5ec
Create Date: 2025-10-20 21:53:31.151091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98a0105ab8f'
down_revision = '1b1fb5e0c5ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('search_keywords', sa.String(length=500), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('total_sent_count', sa.Integer(), nullable=True),
    sa.Column('daily_sent_count', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_jobs_campaign_id'), 'automation_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_created_at'), 'automation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_status'), 'automation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_automation_jobs_user_id'), 'automation_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_jobs_user_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_status'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_created_at'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_campaign_id'), table_name='automation_jobs')
    op.drop_table('automation_jobs')
    # ### end Alembic commands ###
