"""add_automation_mode_to_jobs

Revision ID: 2ee1de14892b
Revises: e98a0105ab8f
Create Date: 2025-10-21 20:25:47.635309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee1de14892b'
down_revision = 'e98a0105ab8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_jobs', sa.Column('automation_mode', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_automation_jobs_automation_mode'), 'automation_jobs', ['automation_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_jobs_automation_mode'), table_name='automation_jobs')
    op.drop_column('automation_jobs', 'automation_mode')
    # ### end Alembic commands ###
